theme: jekyll-theme-cayman
title: Clustering, K-Means Clustering, Hierarchical Clustering, and one relevant Applied Exercise
description: Team 11: Evan Markley, Yuan Fang, Zach Pedini
description: Talk is cheap. Show you the CODE.
